allowBuilds:
  '@biomejs/biome': true
  cpu-features: false
  electron: true
  esbuild: false
  node-pty: true
  ssh2: false

ignoredBuiltDependencies:
  - cpu-features
  - esbuild
  - ssh2

onlyBuiltDependencies:
  - electron
  - node-pty
